--------------------------------------------------------
--  File created - 월요일-6월-05-2023   
--------------------------------------------------------
REM INSERTING into BYUL.AUTHORITIES
SET DEFINE OFF;
Insert into BYUL.AUTHORITIES (AUT_USRID,AUT_AUTHORITY) values ('seller','ROLE_SELLER');
Insert into BYUL.AUTHORITIES (AUT_USRID,AUT_AUTHORITY) values ('member','ROLE_MEMBER');
Insert into BYUL.AUTHORITIES (AUT_USRID,AUT_AUTHORITY) values ('U67bb8f391a8f9e0213cf96920781dcc0','ROLE_MEMBER');
Insert into BYUL.AUTHORITIES (AUT_USRID,AUT_AUTHORITY) values ('112140148672458809387','ROLE_MEMBER');
Insert into BYUL.AUTHORITIES (AUT_USRID,AUT_AUTHORITY) values ('2775117575','ROLE_MEMBER');
Insert into BYUL.AUTHORITIES (AUT_USRID,AUT_AUTHORITY) values ('member_db1','ROLE_MEMBER');
Insert into BYUL.AUTHORITIES (AUT_USRID,AUT_AUTHORITY) values ('member_db2','ROLE_MEMBER');
Insert into BYUL.AUTHORITIES (AUT_USRID,AUT_AUTHORITY) values ('member_db3','ROLE_MEMBER');
Insert into BYUL.AUTHORITIES (AUT_USRID,AUT_AUTHORITY) values ('seller_db1','ROLE_SELLER');
Insert into BYUL.AUTHORITIES (AUT_USRID,AUT_AUTHORITY) values ('seller_db2','ROLE_SELLER');
Insert into BYUL.AUTHORITIES (AUT_USRID,AUT_AUTHORITY) values ('seller_db3','ROLE_SELLER');
Insert into BYUL.AUTHORITIES (AUT_USRID,AUT_AUTHORITY) values ('abcdefg','ROLE_UNAUTHENTICATED');
Insert into BYUL.AUTHORITIES (AUT_USRID,AUT_AUTHORITY) values ('zxcvzxcvzxcv','ROLE_MEMBER');
Insert into BYUL.AUTHORITIES (AUT_USRID,AUT_AUTHORITY) values ('asdfasdf','ROLE_MEMBER');
Insert into BYUL.AUTHORITIES (AUT_USRID,AUT_AUTHORITY) values ('fdfdf','ROLE_MEMBER');
Insert into BYUL.AUTHORITIES (AUT_USRID,AUT_AUTHORITY) values ('qwerqwer','ROLE_MEMBER');
