
/* 구매자 판매자 계정 생성 예시 */
/* db 변경 미반영 */
--구매자 
--BYUL
INSERT INTO USR VALUES (
    'BYUL', 'aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa', DEFAULT, 
    'KANG', 'HAN BYUL', '01024002400', 'byulzdeep@gmail.com', 'tokyo', 'IMAGE');
INSERT INTO BUY VALUES('BYUL', '2400', 'M', TO_DATE('19940602', 'YYYYMMDD'));
--FRIEND
INSERT INTO USR VALUES (
    'FRIEND', 'aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa', DEFAULT, 
    'FRIEND', 'FRIEND BYUL', '01024002400', 'friend@gmail.com', 'tokyo', 'IMAGE');
INSERT INTO BUY VALUES('FRIEND', '2400', 'M', TO_DATE('19940602', 'YYYYMMDD'));
--FRIEND2
INSERT INTO USR VALUES (
    'FRIEND2', 'aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa', DEFAULT, 
    'FRIEND2', 'FRIEND2', '01024002400', 'friend2@gmail.com', 'tokyo', 'IMAGE');
INSERT INTO BUY VALUES('FRIEND2', '2400', 'M', TO_DATE('19940602', 'YYYYMMDD'));
--판매자
--BYULMART
INSERT INTO USR VALUES (
    'BYULMART', 'aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa', DEFAULT, 
    '강', '한별', '01024002400', 'randomEmail', 'tokyo', 'IMAGE');
INSERT INTO SEL VALUES('BYULMART', '한별마트', '최고의 품질을 자랑합니다');
/* 스프링 시큐리티 */
INSERT INTO AUTHORITIES VALUES ('BYUL', 'ROLE_BUYER');
INSERT INTO AUTHORITIES VALUES ('FRIEND', 'ROLE_BUYER');
INSERT INTO AUTHORITIES VALUES ('FRIEND2', 'ROLE_BUYER');
INSERT INTO AUTHORITIES VALUES ('BYULMART', 'ROLE_SELLER');
DESC AUTHORITIES;
SELECT * FROM USR, AUT WHERE USR_ID = AUT_USRID AND USR_ID = 'BYUL';
SELECT * FROM USR, AUT WHERE USR_ID = AUT_USRID AND USR_ID = 'FRIEND';
SELECT * FROM USR, AUT WHERE USR_ID = AUT_USRID AND USR_ID = 'FRIEND2';
SELECT * FROM USR, AUT WHERE USR_ID = AUT_USRID AND USR_ID = 'BYULMART';
/* 친구 추가 프로세스 */
--친구 목록 확인
SELECT * FROM FRI WHERE FRI_SENDER = 'BYUL' OR FRI_RECEIVER = 'BYUL' AND FRI_STATE = 'CN';
--BYUL이 FRIEND에게 친구 추가 요청
INSERT INTO FRI VALUES ('BYUL', 'FRIEND', DEFAULT, 'ST');
SELECT * FROM FRI WHERE FRI_SENDER = 'BYUL' AND FRI_STATE = 'ST';
--FRIEND가 친구 추가 요청 확인
SELECT * FROM FRI WHERE FRI_RECEIVER = 'FRIEND' AND FRI_STATE = 'ST';
--FRIEND가 BYUL의 친구 추가 요청 수락
UPDATE FRI SET FRI_STATE = 'CL' WHERE FRI_RECEIVER = 'FRIEND' AND FRI_SENDER = 'BYUL';
SELECT * FROM FRI WHERE FRI_RECEIVER = 'FRIEND' AND FRI_STATE = 'CL';
--BYUL이 FRIEND가 친구 추가 요청 수락했다는 알림 발견
SELECT * FROM FRI WHERE FRI_SENDER = 'BYUL' AND FRI_STATE = 'CL';
--알림을 눌러서 알림 내용 열람
UPDATE FRI SET FRI_STATE = 'CN' WHERE FRI_SENDER = 'BYUL' AND FRI_RECEIVER = 'FRIEND';
--친구 추가 프로세스 종료
SELECT * FROM FRI WHERE FRI_RECEIVER = 'BYUL' OR FRI_SENDER = 'BYUL' AND FRI_STATE = 'CN';
/* 주문 프로세스 */
DESC PRO;
INSERT INTO PRO VALUES ('BYULMART', PRO_CODE.NEXTVAL, 'CL', '도마뱀목도리', 2400, 5, '목도리 도마뱀 소재로 만든 최고의 도마뱀 목도리', 'F');
INSERT INTO PRO VALUES ('BYULMART', PRO_CODE.NEXTVAL, 'CL', '소갈비', 2400, 10, '맛있음', 'F');
--상품 확인, 재고 확인 하는게 포인트
SELECT * FROM PRO WHERE PRO_SELID = 'BYULMART';
--카트에 추가, 수량이 재고 보다 큰지 JAVA로 제어
INSERT INTO ORD VALUES (DEFAULT, 'BYUL', DEFAULT, DEFAULT);
INSERT INTO ODT VALUES (DEFAULT, 'BYUL', 'BYULMART', 1, 3, 'FRIEND', 'ST');
INSERT INTO ODT VALUES (DEFAULT, 'BYUL', 'BYULMART', 2, 10, 'FRIEND2', 'ST');
--주문번호 VIEW
CREATE OR REPLACE VIEW ORDERINFO AS 
SELECT 
    TO_CHAR(ORD_DATE, 'YYYYMMDDHH24MISS') || ORD_BUYID || ORD_PAYCODE AS ORDERCODE,
    ORD_BUYID AS BUYID
FROM ORD;
--20230427051841BYULNA
SELECT * FROM ORDERINFO WHERE BUYID = 'BYUL';
--결제 진행
UPDATE ORD SET 
    ORD_DATE = SYSDATE, ORD_OSTSTATE = 'OC', ORD_PAYCODE = 'KK'
    WHERE ORD_DATE = TO_DATE ('20230427051841', 'YYYYMMDDHH24MISS') AND ORD_BUYID = 'BYUL';
--ODT 테이블은 트리거(WHITEBOX.SQL참고)로 자동 업데이트된다.
--트리거를 쓰는 이유는 오라클은 ON UPDATE CASCADE를 지원하지 않기 때문.
SELECT * FROM ORDERINFO WHERE BUYID = 'BYUL';
--20230427041511BYULKK
--재고 수정
UPDATE PRO SET PRO_STOCK = ( SELECT PRO_STOCK FROM PRO WHERE PRO_SELID = 'BYULMART' AND PRO_CODE = 1 ) - 3 WHERE PRO_SELID = 'BYULMART' AND PRO_CODE = 1;
UPDATE PRO SET PRO_STOCK = ( SELECT PRO_STOCK FROM PRO WHERE PRO_SELID = 'BYULMART' AND PRO_CODE = 2 ) - 10 WHERE PRO_SELID = 'BYULMART' AND PRO_CODE = 2;
SELECT * FROM PRO;
--선물 확인
SELECT * FROM ODT WHERE ODT_ORDBUYID = 'BYUL';
SELECT * FROM ODT WHERE ODT_BUYRECIPIENT = 'FRIEND';
SELECT * FROM ODT WHERE ODT_BUYRECIPIENT = 'FRIEND2';
--선물 수락 ( 알림 클릭? )
--20230427051904BYULKK
SELECT * FROM ORDERINFO WHERE BUYID = 'BYUL';
UPDATE ODT SET ODT_GSTCODE = 'CL' 
WHERE ODT_ORDDATE = TO_DATE ('20230427051904', 'YYYYMMDDHH24MISS') AND 
    ODT_ORDBUYID = 'BYUL' AND
    ODT_PROSELID = 'BYULMART' AND
    ODT_PROCODE = 1 AND 
    ODT_BUYRECIPIENT = 'FRIEND';
UPDATE ODT SET ODT_GSTCODE = 'CL' 
WHERE 
    ODT_ORDDATE = TO_DATE ('20230427051904', 'YYYYMMDDHH24MISS') AND 
    ODT_ORDBUYID = 'BYUL' AND
    ODT_PROSELID = 'BYULMART' AND
    ODT_PROCODE = 2 AND 
    ODT_BUYRECIPIENT = 'FRIEND2';
--상대 선물 수령 확인 ( 선택 ? )
SELECT * FROM ODT WHERE ODT_ORDBUYID = 'BYUL' AND ODT_GSTCODE = 'CL';
--알림 버튼 클릭
UPDATE ODT SET ODT_GSTCODE = 'CN'
WHERE
    ODT_ORDDATE = TO_DATE ('20230427051904', 'YYYYMMDDHH24MISS') AND 
    ODT_ORDBUYID = 'BYUL' AND
    ODT_PROSELID = 'BYULMART' AND
    ODT_PROCODE = 1 AND 
    ODT_BUYRECIPIENT = 'FRIEND';
UPDATE ODT SET ODT_GSTCODE = 'CN'
WHERE
    ODT_ORDDATE = TO_DATE ('20230427051904', 'YYYYMMDDHH24MISS') AND 
    ODT_ORDBUYID = 'BYUL' AND
    ODT_PROSELID = 'BYULMART' AND
    ODT_PROCODE = 2 AND 
    ODT_BUYRECIPIENT = 'FRIEND2';
