--------------------------------------------------------
--  File created - 월요일-6월-05-2023   
--------------------------------------------------------
REM INSERTING into BYUL.USERS
SET DEFINE OFF;
Insert into BYUL.USERS (USR_ID,USR_PASSWORD,USR_ENABLED,USR_LASTNAME,USR_FIRSTNAME,USR_PHONE,USR_EMAIL,USR_ADDRESS,USR_IMAGE,USR_DATE) values ('member_db1','$2a$10$vJInotHMkCEld9dnIoEizunuZENiDnUwlbKc6Rlnzl36bjXumNQdG','1','Member','DBOne','DhDpp7bSzP8g1Q7XIqboVg==','iIFsrQO1znYdUp1FedA42nx15kJJ2JjOFvKVoB7nPfQ=','cdvDWlF8UvYBnNEuRMRktw==','/res/img/whitebox_logo_p.png',to_date('23/05/29','RR/MM/DD'));
Insert into BYUL.USERS (USR_ID,USR_PASSWORD,USR_ENABLED,USR_LASTNAME,USR_FIRSTNAME,USR_PHONE,USR_EMAIL,USR_ADDRESS,USR_IMAGE,USR_DATE) values ('member_db2','$2a$10$VcLBcbRiKVxBTyqcwF635.gEnZxvUBMh9vELfvb3pAAuTfTWVoLky','1','Member','DBTwo','DhDpp7bSzP8g1Q7XIqboVg==','iIFsrQO1znYdUp1FedA42nx15kJJ2JjOFvKVoB7nPfQ=','cdvDWlF8UvYBnNEuRMRktw==','/res/img/whitebox_logo_p.png',to_date('23/05/29','RR/MM/DD'));
Insert into BYUL.USERS (USR_ID,USR_PASSWORD,USR_ENABLED,USR_LASTNAME,USR_FIRSTNAME,USR_PHONE,USR_EMAIL,USR_ADDRESS,USR_IMAGE,USR_DATE) values ('member_db3','$2a$10$ClopkWImbo212zA4wgnDMeO7VAlI4wTX3yjzxWRj1PGxT0.DCKJl6','1','Member','DBThree','DhDpp7bSzP8g1Q7XIqboVg==','iIFsrQO1znYdUp1FedA42nx15kJJ2JjOFvKVoB7nPfQ=','cdvDWlF8UvYBnNEuRMRktw==','/res/img/whitebox_logo_p.png',to_date('23/05/29','RR/MM/DD'));
Insert into BYUL.USERS (USR_ID,USR_PASSWORD,USR_ENABLED,USR_LASTNAME,USR_FIRSTNAME,USR_PHONE,USR_EMAIL,USR_ADDRESS,USR_IMAGE,USR_DATE) values ('seller_db1','$2a$10$EDsRZuvbjrCs0.5cocQo2.aBrgJWbiNXX/ee53VMh5D81y2pXQfca','1','洋服屋','洋服屋','5vowcoiYy0qQSieLKfNP1Q==','DyDExiAKTJAxwNDKmr8CALqLcD5HDIEzOCjwzT3j21Y=','ARkn42UuvMdDhNgilXZrgw==','/res/img/whitebox_logo_p.png',to_date('23/05/29','RR/MM/DD'));
Insert into BYUL.USERS (USR_ID,USR_PASSWORD,USR_ENABLED,USR_LASTNAME,USR_FIRSTNAME,USR_PHONE,USR_EMAIL,USR_ADDRESS,USR_IMAGE,USR_DATE) values ('seller_db2','$2a$10$.JB/amCfkXdIx4cPIlK3UuBnLg4PSZ5hYdUPhlYcGnEvGFjI1JEcS','1','電子機器屋','電子機器屋','sbtF7WmzJQKf8mE6IUofjA==','DyDExiAKTJAxwNDKmr8CALqLcD5HDIEzOCjwzT3j21Y=','ARkn42UuvMdDhNgilXZrgw==','/res/img/whitebox_logo_p.png',to_date('23/05/29','RR/MM/DD'));
Insert into BYUL.USERS (USR_ID,USR_PASSWORD,USR_ENABLED,USR_LASTNAME,USR_FIRSTNAME,USR_PHONE,USR_EMAIL,USR_ADDRESS,USR_IMAGE,USR_DATE) values ('seller_db3','$2a$10$JlNtRwi/ss2EFkevu3fZtOLs5/3hojBt68fJaeDdGzE9RUwMcFcYe','1','誕生日プレゼント屋','誕生日プレゼント屋','sbtF7WmzJQKf8mE6IUofjA==','DyDExiAKTJAxwNDKmr8CALqLcD5HDIEzOCjwzT3j21Y=','ARkn42UuvMdDhNgilXZrgw==','/res/img/whitebox_logo_p.png',to_date('23/05/29','RR/MM/DD'));
