--------------------------------------------------------
--  File created - 월요일-6월-05-2023   
--------------------------------------------------------
REM INSERTING into BYUL.VIEWHISTORY
SET DEFINE OFF;
Insert into BYUL.VIEWHISTORY (VHS_USRMEMID,VHS_PROUSRSELID,VHS_PROCODE,VHS_DATE,VHS_ISVIEWED,VHS_ISWATCHED,VHS_ISWISHED) values ('member_db1','seller_db1',1,to_date('23/05/29','RR/MM/DD'),'T','T','T');
Insert into BYUL.VIEWHISTORY (VHS_USRMEMID,VHS_PROUSRSELID,VHS_PROCODE,VHS_DATE,VHS_ISVIEWED,VHS_ISWATCHED,VHS_ISWISHED) values ('member_db1','seller_db1',2,to_date('23/05/29','RR/MM/DD'),'T','T','T');
Insert into BYUL.VIEWHISTORY (VHS_USRMEMID,VHS_PROUSRSELID,VHS_PROCODE,VHS_DATE,VHS_ISVIEWED,VHS_ISWATCHED,VHS_ISWISHED) values ('member_db1','seller_db1',3,to_date('23/05/29','RR/MM/DD'),'T','T','T');
Insert into BYUL.VIEWHISTORY (VHS_USRMEMID,VHS_PROUSRSELID,VHS_PROCODE,VHS_DATE,VHS_ISVIEWED,VHS_ISWATCHED,VHS_ISWISHED) values ('member_db1','seller_db1',4,to_date('23/05/29','RR/MM/DD'),'T','T','T');
Insert into BYUL.VIEWHISTORY (VHS_USRMEMID,VHS_PROUSRSELID,VHS_PROCODE,VHS_DATE,VHS_ISVIEWED,VHS_ISWATCHED,VHS_ISWISHED) values ('member_db1','seller_db1',5,to_date('23/05/29','RR/MM/DD'),'T','T','T');
Insert into BYUL.VIEWHISTORY (VHS_USRMEMID,VHS_PROUSRSELID,VHS_PROCODE,VHS_DATE,VHS_ISVIEWED,VHS_ISWATCHED,VHS_ISWISHED) values ('member_db1','seller_db1',6,to_date('23/05/29','RR/MM/DD'),'T','T','T');
Insert into BYUL.VIEWHISTORY (VHS_USRMEMID,VHS_PROUSRSELID,VHS_PROCODE,VHS_DATE,VHS_ISVIEWED,VHS_ISWATCHED,VHS_ISWISHED) values ('member_db1','seller_db1',7,to_date('23/05/29','RR/MM/DD'),'T','T','T');
Insert into BYUL.VIEWHISTORY (VHS_USRMEMID,VHS_PROUSRSELID,VHS_PROCODE,VHS_DATE,VHS_ISVIEWED,VHS_ISWATCHED,VHS_ISWISHED) values ('member_db1','seller_db1',8,to_date('23/05/29','RR/MM/DD'),'T','T','T');
Insert into BYUL.VIEWHISTORY (VHS_USRMEMID,VHS_PROUSRSELID,VHS_PROCODE,VHS_DATE,VHS_ISVIEWED,VHS_ISWATCHED,VHS_ISWISHED) values ('member_db2','seller_db2',1,to_date('23/05/29','RR/MM/DD'),'T','T','T');
Insert into BYUL.VIEWHISTORY (VHS_USRMEMID,VHS_PROUSRSELID,VHS_PROCODE,VHS_DATE,VHS_ISVIEWED,VHS_ISWATCHED,VHS_ISWISHED) values ('member_db2','seller_db2',2,to_date('23/05/29','RR/MM/DD'),'T','T','T');
Insert into BYUL.VIEWHISTORY (VHS_USRMEMID,VHS_PROUSRSELID,VHS_PROCODE,VHS_DATE,VHS_ISVIEWED,VHS_ISWATCHED,VHS_ISWISHED) values ('member_db2','seller_db2',3,to_date('23/05/29','RR/MM/DD'),'T','T','T');
Insert into BYUL.VIEWHISTORY (VHS_USRMEMID,VHS_PROUSRSELID,VHS_PROCODE,VHS_DATE,VHS_ISVIEWED,VHS_ISWATCHED,VHS_ISWISHED) values ('member_db2','seller_db2',4,to_date('23/05/29','RR/MM/DD'),'T','T','T');
Insert into BYUL.VIEWHISTORY (VHS_USRMEMID,VHS_PROUSRSELID,VHS_PROCODE,VHS_DATE,VHS_ISVIEWED,VHS_ISWATCHED,VHS_ISWISHED) values ('member_db2','seller_db2',5,to_date('23/05/29','RR/MM/DD'),'T','T','T');
Insert into BYUL.VIEWHISTORY (VHS_USRMEMID,VHS_PROUSRSELID,VHS_PROCODE,VHS_DATE,VHS_ISVIEWED,VHS_ISWATCHED,VHS_ISWISHED) values ('member_db2','seller_db2',6,to_date('23/05/29','RR/MM/DD'),'T','T','T');
Insert into BYUL.VIEWHISTORY (VHS_USRMEMID,VHS_PROUSRSELID,VHS_PROCODE,VHS_DATE,VHS_ISVIEWED,VHS_ISWATCHED,VHS_ISWISHED) values ('member_db2','seller_db2',7,to_date('23/05/29','RR/MM/DD'),'T','T','T');
Insert into BYUL.VIEWHISTORY (VHS_USRMEMID,VHS_PROUSRSELID,VHS_PROCODE,VHS_DATE,VHS_ISVIEWED,VHS_ISWATCHED,VHS_ISWISHED) values ('member_db3','seller_db3',1,to_date('23/05/29','RR/MM/DD'),'T','T','T');
Insert into BYUL.VIEWHISTORY (VHS_USRMEMID,VHS_PROUSRSELID,VHS_PROCODE,VHS_DATE,VHS_ISVIEWED,VHS_ISWATCHED,VHS_ISWISHED) values ('member_db3','seller_db3',2,to_date('23/05/29','RR/MM/DD'),'T','T','T');
Insert into BYUL.VIEWHISTORY (VHS_USRMEMID,VHS_PROUSRSELID,VHS_PROCODE,VHS_DATE,VHS_ISVIEWED,VHS_ISWATCHED,VHS_ISWISHED) values ('member_db3','seller_db3',3,to_date('23/05/29','RR/MM/DD'),'T','T','T');
Insert into BYUL.VIEWHISTORY (VHS_USRMEMID,VHS_PROUSRSELID,VHS_PROCODE,VHS_DATE,VHS_ISVIEWED,VHS_ISWATCHED,VHS_ISWISHED) values ('member_db3','seller_db3',4,to_date('23/05/29','RR/MM/DD'),'T','T','T');
Insert into BYUL.VIEWHISTORY (VHS_USRMEMID,VHS_PROUSRSELID,VHS_PROCODE,VHS_DATE,VHS_ISVIEWED,VHS_ISWATCHED,VHS_ISWISHED) values ('member_db3','seller_db3',5,to_date('23/05/29','RR/MM/DD'),'T','T','T');
Insert into BYUL.VIEWHISTORY (VHS_USRMEMID,VHS_PROUSRSELID,VHS_PROCODE,VHS_DATE,VHS_ISVIEWED,VHS_ISWATCHED,VHS_ISWISHED) values ('member_db3','seller_db3',6,to_date('23/05/29','RR/MM/DD'),'T','T','T');
Insert into BYUL.VIEWHISTORY (VHS_USRMEMID,VHS_PROUSRSELID,VHS_PROCODE,VHS_DATE,VHS_ISVIEWED,VHS_ISWATCHED,VHS_ISWISHED) values ('member_db3','seller_db3',7,to_date('23/05/29','RR/MM/DD'),'T','T','T');
Insert into BYUL.VIEWHISTORY (VHS_USRMEMID,VHS_PROUSRSELID,VHS_PROCODE,VHS_DATE,VHS_ISVIEWED,VHS_ISWATCHED,VHS_ISWISHED) values ('member_db3','seller_db3',8,to_date('23/05/29','RR/MM/DD'),'T','T','T');
